<a href="https://colab.research.google.com/github/hyevvon/ESAA/blob/main/ESAA_assignment_week1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CHAPTER 1 **<파이썬 기반의 머신러닝과 생태계 이해>**
## [개념 정리]

---

## 1-1. 머신러닝 분류
*   지도학습: 분류, 회귀, 추천 시스템, 시각/음성 감지/인지
*   비지도학습: 클러스터링, 차원 축소, 강화학습
---
## 1-3. 넘파이

> **넘파이**: 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적 패키지.

*  빠른 배열 연산 속도
*  C/C++ 기반 타 프로그램과의 호환 API  제공 (수행 성능이 매우 중요한 부분을 다룰 때 활용) / 텐서플로와 호환
*  다양한 데이터 핸들링 기능 (판다스 보다는 부족)
*  많은 머신러닝 알고리즘 작성의 기반

> **넘파이 ndarray 개요**

*  넘파이 기반 데이터 type: ndarray
*  np.array(): 다양한 인자를 ndarray로 변환
*  ndarray.shape: ndarray의 차원, 크기를 튜플 형태로 나타냄
*  차원을 명확히 하는 것이 중요 (데이터값 동일, 차원 다른 경우 오류 발생 빈번)
*  ndarray.ndim: array의 차원 확인

> **ndarray 데이터 타입**

* 숫자값(int, unsigned int, float)/문자열 값/불 값/complex 타입
* 한 개의 ndarray 안에 같은 데이터 타입만 가능. -> 다른 타입이 섞인 리스트가 입력되면, 크기가 더 큰 타입으로 형 변환 ex. int&string -> string, int&float -> float
* ndarray.dtype: 데이터 타입 확인
* ndarray.astype(): 데이터 타입 변경. 원하는 타입을 문자열로 지정

> **ndarray를 편리하게 생성하기**

* 주로 테스트용 데이터 생성, 대규모 데이터를 일괄적으로 초기화 할 때 사용.
* np.arrange(): 0부터 stop값-1 까지의 숫자값을 순차적으로 ndarray 데이터값으로 변환 /start=, stop= 지정 가능
* np.zeros(): 모든 값을 0으로 채운, 입력한 shape의 ndarray 반환 / dtype= 지정 가능, 디폴트-float64
* np.ones(): 모든 값을 1로 채운, 입력한 shape의 ndarray 반환 / dtype= 지정 가능, 디폴트-float64

> **ndarray의 차원, 크기를 변경하는 reshape()**

* .reshape():ndarray를 특정 차원 및 크기로 변환. 원하는 크기 지정.
* 변경이 불가능(호환 불가능)하면 오류 발생
* [인자로 -1 적용] 칼럼, 로우 중 고정된 인자에 맞는 칼럼(로우)를 자동으로 생성해 변환 / (-1,1) << 반드시 1개의 칼럼을 가진 ndarray 변환
* .tolist(): ndarray를 리스트로 변환

> **인덱싱**

1. 단일 값 추출
* 한 개의 데이터 추출
* [] 안에 위치값 입력 (0부터 시작)
* -(마이너스)는 맨 뒤부터 순서.
* 데이터값 수정에 사용 가능
* 다차원 ndarray 의 경우, (row=, col=)==(axis0=, axis1=)로 지정 / axis2는 높이

2. 슬라이싱
* : 기호를 사용해 연속한 데이터 추출 (>ndarray 타입으로 추출)
* 시작 인덱스값:종료 인덱스값 >> '시작~종료-1' 데이터 추출
* 인덱스 생략: 자동으로 맨 처음(마지막) 인덱스로 간주.
* 다차원 ndarray의 경우, axis 마다 슬라이싱 적용 (단일값 인덱스랑 혼용 가능)
* 다차원에서 뒤에 오는 인덱스를 없애면, 한 차원 아래의 ndarray 반환

3. 팬시 인덱싱
* 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환.

4. 불린 인덱싱

* 조건 필터링과 검색 동시에 가능.
* [] 내에 조건문 기재
* 내부 동작 순서: True 값에 해당하는 인덱스값만 저장 (1 저장 x, true인 인덱스값 저장o) >> 해당하는 인덱스 위치에 있는 데이터의 ndarray 반환


> **행렬의 정렬 - sort()와 argsort()**

* np.sort(): 원 행렬 유지 & 정렬된 행렬 반환
* ndarray.sort(): 원 행렬을 정렬해서 반환(원본 행렬 자체를 변경) / 반환값은 None
* 디폴트: 오름차순
* 내림차순: np.sort()[::-1]
* 다차원의 경우, axis 값 설정을 통해 정렬 방향 지정
* [정렬된 행렬의 (원본) 인덱스 반환] np.argsort() / np.argsort()[::-1]
* 넘파이는 메타 데이터를 가질 수 없으므로, 값과 메타데이터를 별도의 ndarray 로 가져야함.

> **행렬 내적, 전치 행렬 구하기**

1. 행렬 내적 (행렬 곱)
* np.dot() 을 이용해 계산
* 계산 가능 조건: 왼쪽 행렬 열 개수 = 오른쪽 행렬 행 개수

2. 전치 행렬
* 전치 행렬: 원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬
* transport() 로 계산


In [4]:
import numpy as np
array1=np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2=np.array([[1,2,3],[2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3=np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [3]:
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1: 1차원, array2: 2차원, array3: 2차원


In [5]:
list1=[1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [4]:
list2=[1,2,'test']
array2=np.array(list2)
print(array2, array2.dtype)

list3=[1,2,3.0]
array3=np.array(list3)
print(array3,array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [6]:
array_int = np.array ([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1= array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array ([1.1, 2.1, 3.1])
array_int2= array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [8]:
sequence_array = np. arange(10)
print (sequence_array)
print (sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [5]:
zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array)
print (zero_array.dtype, zero_array .shape)

one_array = np.ones ((3, 2))
print (one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [6]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2, 5)
print('array2:\n', array2)

array3 = array1.reshape(5, 2)
print ('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [7]:
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [9]:
array1 = np.arange (10)
print(array1)

array2 = array1.reshape(-1, 5)
print('array2 shape:', array2.shape)
array3 = array1.reshape(5, -1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [10]:
array1 = np.arange (10)
array4 = array1.reshape(-1, 4)

ValueError: cannot reshape array of size 10 into shape (4)

In [11]:
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print('array3d: \n', array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1, 1)
print('array5:\n', array5.tolist())
print( 'array5 shape:', array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1 .reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d: 
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


In [13]:
# 1부터 9까지의 1차원 ndarray 생성
array1=np.arange(start=1,stop=10)
print('array1:', array1)
# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value=array1[2]
print('value:',value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [14]:
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [16]:
array1[0] = 9
array1[8] = 0
print('array1：',array1)

array1： [9 2 3 4 5 6 7 8 0]


In [20]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

print('(row=0, co1=0) index 가리키는 값:', array2d[0, 0])
print('(row=O, col=1) index 가리키는 값:', array2d[0, 1])
print('(row=1, col=0) index 가리키는 값:', array2d[1, 0])
print('(row=2, col=2) index 가리키는 값:', array2d[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, co1=0) index 가리키는 값: 1
(row=O, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


In [21]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [22]:
array1 = np .arange(start=1, stop=10)
array4 = array1 [:3]
print(array4)
array5 = array1[3:]
print(array5)
array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [23]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print('array2d:\n',array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[ :2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [25]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


In [26]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)

array3 = array2d[[0, 1], 2]
print('array2d|[0, 1], 2] =>', array3.tolist())

array4 = array2d[[0, 1], 0:2]
print('array2d[[0, 1], 0:2] => ', array4.tolist())

array5 = array2d[[0, 1]]
print('array2d[[0, 1]] => ', array5.tolist())

array2d|[0, 1], 2] => [3, 6]
array2d[[0, 1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0, 1]] =>  [[1, 2, 3], [4, 5, 6]]


In [27]:
array1d = np.arange(start=1, stop=10)
# [ ] 안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [28]:
array1d>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [29]:
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [30]:
indexes = np.array ([5, 6, 7, 8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과:', array4)

일반 인덱스로 필터링 결과: [6 7 8 9]


In [34]:
org_array = np.array([ 3, 1, 9, 5])
print('원본 행렬:', org_array)
# np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)
#ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array sort() 호출 후 반환된 행렬:' , sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [35]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [36]:
array2d = np.array([[8, 12],[7, 1 ]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [37]:
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print (type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [38]:
org_array = np .array ([3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [40]:
import numpy as np

name_array = np.array (['John','Mike', 'Sarah', 'Kate', 'Samuel' ])
score_array= np. array ([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


In [42]:
A= np.array( [[1, 2, 3],[4, 5, 6]] )
B = np.array([(7, 8),[9, 10],[11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [43]:
A = np.array ([[1, 2],[3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
