# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
array1=np.zeros(10)
print(array1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [4]:
array2=np.zeros(10)
array2[4]=1
print(array2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [5]:
array3=np.arange(start=10,stop=50)
print(array3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [7]:
array3_reverse=np.sort(array3)[::-1]
print(array3_reverse)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [8]:
array4=np.arange(start=0,stop=9).reshape(3,3)
print(array4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
array5=np.array([1,2,0,0,4,0])
print(array5[array5 != 0])
# 인덱스 출력 어떻게..?

[1 2 4]


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [9]:
np.random.random((3,3,3))

array([[[0.4207483 , 0.55719181, 0.70672049],
        [0.33231599, 0.09703159, 0.73033718],
        [0.82335277, 0.85764826, 0.10096476]],

       [[0.10007606, 0.39042029, 0.00270838],
        [0.86897636, 0.14215793, 0.41051778],
        [0.26885234, 0.69433598, 0.38173692]],

       [[0.12555479, 0.97431672, 0.32866168],
        [0.87654586, 0.4482487 , 0.57570514],
        [0.11598197, 0.18035226, 0.0505058 ]]])

#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [13]:
array6=np.random.random((10,10))
print(array6,'\n',np.min(array6),'\n',np.max(array6))

[[0.69408345 0.88388374 0.23529555 0.72613791 0.67585274 0.34410764
  0.13991095 0.8011044  0.94769542 0.69870509]
 [0.35488042 0.77432256 0.28977797 0.68509308 0.2783512  0.00696548
  0.55533496 0.4253396  0.0171596  0.76911381]
 [0.56271483 0.93158249 0.56192719 0.90086822 0.99299204 0.85796161
  0.85758729 0.63226337 0.64783332 0.75120742]
 [0.47235058 0.04742999 0.14242762 0.55583206 0.78335834 0.64959516
  0.8607939  0.38033861 0.13196749 0.87128114]
 [0.82698438 0.57363058 0.0746619  0.95582258 0.30378112 0.63736362
  0.12102206 0.54147959 0.76788257 0.25630071]
 [0.19123872 0.83552579 0.30138947 0.6832343  0.47295281 0.36900381
  0.59921941 0.34199558 0.73874995 0.28670844]
 [0.10905628 0.88674544 0.54024008 0.11960954 0.30445115 0.35407438
  0.23719977 0.89704738 0.25298363 0.32023955]
 [0.52588234 0.38685886 0.59034675 0.71713539 0.03098606 0.32410964
  0.77067939 0.24817282 0.58220722 0.00389772]
 [0.79321996 0.52346833 0.56839161 0.87155054 0.44696642 0.20171716
  0.59867275

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [14]:
array7=np.random.random(30)
print(array7,'\n',np.mean(array7))

[0.25579158 0.12257752 0.29062285 0.08107282 0.97833038 0.17761381
 0.36419887 0.68838774 0.38602401 0.32670601 0.73218418 0.91135632
 0.65968887 0.65418083 0.69773599 0.45359973 0.8575995  0.31788256
 0.54705669 0.96689927 0.67543271 0.94940909 0.59207372 0.06535077
 0.88721185 0.31403    0.05042746 0.90309428 0.31364702 0.17476549] 
 0.5131650633883471


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan, false, false, nan, true, false

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [19]:
array8=np.zeros((5, 5))
array8[(1,0)]=1
array8[(2,1)]=2
array8[(3,2)]=3
array8[(4,3)]=4

print(array8)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [23]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [26]:
array9=np.random.random((5,5))
array9_norm=(array9-np.mean(array9))/np.std(array9)
print(array9,"\n",'\n',array9_norm)

[[0.05511131 0.81584783 0.88984219 0.83540588 0.29739424]
 [0.42783249 0.1324503  0.90667297 0.44744864 0.03339922]
 [0.42791263 0.17986829 0.63690727 0.1850479  0.36612918]
 [0.402531   0.64192612 0.76695851 0.47608384 0.25535917]
 [0.68763625 0.64898547 0.91528088 0.03533847 0.51577067]] 
 
 [[-1.51136276  1.19893906  1.46256129  1.26861922 -0.64817314]
 [-0.18345635 -1.2358245   1.52252487 -0.11356923 -1.58871715]
 [-0.18317082 -1.06688685  0.56142148 -1.04843325 -0.40328885]
 [-0.27359885  0.57930231  1.02475944 -0.01154965 -0.79793292]
 [ 0.74215532  0.60445288  1.55319258 -1.58180812  0.12984399]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

*   Python Built-in sum Function: The sum of range(5) (which is 0 + 1 + 2 + 3 + 4 = 10) is computed, and then -1 is added to it. The result will be 9
*   NumPy's sum Function: NumPy's sum function doesn't treat the second argument as a start value like Python's built-in sum. Instead, it treats it as an axis parameter. Since -1 is not a valid axis for a 1D sequence (the valid axis for a 1D array is 0), NumPy will raise a TypeError


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 32. Create a random vector of size 10 and sort it (★★☆)

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
# column 3

In [ ]:
# column 2


In [ ]:
# column 3
