<a href="https://colab.research.google.com/github/hyevvon/ESAA/blob/main/YB0307_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
import numpy as np

A=np.random.random((5,3))
B=np.random.random((3,2))

np.dot(a,b)

array([[0.29095622, 1.19947294],
       [0.17410666, 0.83363272],
       [0.38828062, 1.05818625],
       [0.55146316, 1.05160937],
       [0.42672063, 1.29392299]])

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
array22 = np.arange(10)
array22[(array22 > 3) & (array22 < 8)]*=-1
print(array22)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

9, 10

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

유효: 1,2,4,5


무효: 3,6


#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [42]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-42-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
<ipython-input-42-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
<ipython-input-42-2a10de0ee61b>:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


nan, 0, array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [47]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)

print(np.intersect1d(Z1,Z2))

[0 2 7 9]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

False


In [48]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-48-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [ ]:
Z = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [49]:
A=np.random.random(5)
B=np.random.random(5)

np.add(A,B, out=B)
np.negative(A,out=A)
np.divide(A,2,out=A)
np.multiply(B,A,out=A)

array([-0.3969213 , -0.3249562 , -0.01115747, -0.20787412, -0.12225964])

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [50]:
arr30=np.random.uniform(0,10,5)

print(arr30 - arr30%1)
print(arr30 // 1)

[6. 6. 2. 2. 7.]
[6. 6. 2. 2. 7.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
array31=np.random.randint(0,5,25).reshape((5,5))
print(array31)

[[1 2 0 2 0]
 [0 4 4 3 4]
 [4 0 4 0 1]
 [2 2 1 2 0]
 [2 2 2 0 0]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
array32=np.random.random(10)
print(np.sort(array32))

array([0.20579094, 0.2069969 , 0.21516495, 0.27455804, 0.34769442,
       0.43546835, 0.58815566, 0.60025308, 0.69418378, 0.79868594])

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
np.array_equal(A,B)

False

## 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [53]:
arr34=np.random.random((10,2))
X= arr34[:,0]
Y= arr34[:,1]

r = np.sqrt(X**2+Y**2)
t = np.arctan2(Y,X)

print(r,'\n',t)

[0.87136758 0.48876541 0.52688479 0.48672401 1.28541887 0.5579461
 0.86873841 0.91522422 1.01291206 1.15014678] 
 [0.86323489 1.3048727  1.41535025 1.15230922 0.78393323 0.90218457
 0.96452455 0.4627004  0.23477973 0.56869661]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [60]:
Z=np.random.random(10)
Z[Z.argmax()]= 0

print(Z)

[0.30156597 0.31820638 0.         0.25704244 0.79774418 0.19575899
 0.31294261 0.29476952 0.7672817  0.16735867]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [61]:
Z = np.arange(100)
v = np.random.uniform(0,100)

print(Z[(np.abs(Z-v)).argmin()])

19


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [62]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
  print(index,value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [64]:
n = 5
p = 6
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'99')
print(Z)

[[99.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0. 99.  0.  0.  0.]
 [ 0.  0.  0. 99.  0.]
 [99. 99.  0. 99.  0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [65]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,0].argsort()])

[[0 1 3]
 [2 4 0]
 [7 6 8]]
[[0 1 3]
 [2 4 0]
 [7 6 8]]


In [66]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[5 5 8]
 [6 8 4]
 [7 0 1]]
[[7 0 1]
 [5 5 8]
 [6 8 4]]


In [67]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,2].argsort()])

[[7 7 3]
 [5 4 0]
 [2 2 1]]
[[5 4 0]
 [2 2 1]
 [7 7 3]]
