# [개념 필사] - 딥러닝 파이토치

## CHAPTER 01 <머신러닝과 딥러닝>

## **1.1 인공지능, 머신러닝과 딥러닝**

◼**인공지능** : 인간의 지능을 모방하여 사람이 하는 일을 컴퓨터가 할 수 있도록 하는 기술

* 구현 방법: 머신러닝 (전처리 필요) > 딥러닝 (컴퓨터가 스스로 분석)

(사진)

## **1.2 머신러닝이란**

* 훈련 데이터 학습 ▶ 모형 생성 ▶ 새로운 데이터로 결과 예측

* 데이터: 실제 데이터의 특징 반영, 편향되지 않는 데이터가 좋음
* 모델: 학습 단계에서 얻은 최종 결과물
* 지도학습(분류,회귀), 비지도학습(군집, 차원축소), 강화학습

## **1.3 딥러닝이란**

◼**딥러닝**: 인간의 신경망 원리를 모방한 심층 신경망 이론을 기반으로 고안된 머신러닝 방법의 일종

✅ 신경망(심층신경망), 역전파

* 학습 과정

   

1.   데이터 준비
2.   모델 정의: 신경망 생성, 은닉층 개수
3.   모델 컴파일: 활성화 함수, 손실 함수, 옵티마이저 선택
4.   모델 훈련: 한 번에 처리할 데이터양 지정, 에포크 선택
5.   모델 예측



* 지도 학습(합성곱 신경망, 순환 신경망, LSTM): 이미지 분류, 이미지 인식, 이미지 분할, 시계열 데이터 분류

* 비지도 학습(워드 임베딩, 군집): 자연어 처리, 클러스터 분류

* 전이 학습: 사전학습모델을 가지고 원하는 학습에 미세 조정 기법을 이용하여 학습시키는 방법.

## CHAPTER 02 <실습 환경 설정과 파이토치 기초>

## **2.1 파이토치 개요**

💻 파이토치: 딥러닝 프레임워크, GPU에서 텐서 조작 및 동적 신경망 구축이 가능

* GPU: 미분 계산 빠름
* 텐서: 파이토치의 데이터 형태, 단일 데이터 형식으로 된 자료들의 다차원 행렬
* 동적 신경망: 훈련 반복 마다 네트워크 변경이 가능한 신경망

✅ 아키텍처
(사진)

1. 파이토치 API: 사용자 인터페이스 제공, 실제 계산X
* torch - GPU 지원 텐서 패키지
* torch.autograd - 자동 미분 패키지
* torch.nn - 신경망 구축 및 훈련 패키지
* torch.multiprocessing: 파이썬 멀티프로세싱 패키지
* torch.utils: 데이터로드, 기타 유틸리티 제공 패키지

2. 파이토치 엔진
* Autograd C++ - 가중치, 바이어스 업데이트 과정에서 미분 자동 계산
* Aten C++ - 텐서 라이브러리 제공
* JIT C++ - 계산 최적화 컴파일러

3. 연산 처리:
* C, CUDA 패키지 - 상위의 API에서 할당된 거의 모든 계산 수행

## **2.2 파이토치 기초 문법**

✅ 텐서생성 및 변환

✅ 텐서 인덱스 조작: 바로 지정, 슬라이스 등 가능

* torch.FloatTensor - 32비트의 부동 소수점
* torch.DoubleTensor - 64비트의 부동 소수점
* torch.LongTensor - 32비트의 부호가 있는 정수

✅ 텐서 연산 및 차원 조작:
* 다양한 연산 가능, 텐서 간 타입이 일치해야함.
* 차원 조작
```
view - 차원 변경
stack, cat - 차원 결합
t, transpose - 차원 교환
```

> **데이터 준비**

* 이미지 데이터: 분산된 파일에서 데이터 읽은 후, 전처리, 배치 단위로 분할하여 처리

* 텍스트 데이터: 임베딩 과정, 시퀀스를 배치 단위로 분할하여 처리

* 단순하게 파일 불러와서 사용: JSON, PDF, CSV 등의 파일
```
import pandas as pd
import torch
data = pd.read_csv('...')
x = torch.from_numpy(data['x'].values).unsqueeze(dim=1).float()
```
* 커스텀 데이터셋 만들어서 사용: 시간과 비용 효율적으로 데이터를 조금씩 나누어 불러서 사용 / class 구현으로 데이터셋 불러옴 -> torch. utils.data. DataLoader에 파라미터로 전달 / DataLoader: 배치 크기만큼 데이터 반환
```
import pandas as pd
import torch
from torch .utils.data import Dataset
from torch.utils.data import DataLoader
class CustomDataset (Dataset):
  def __ init __ (self, csv_file): ------csv_file 파라미터를 통해 데이터셋을 불러옵니다.
    self.label = pd .read_csv (csv_file)
  def __ len __ (self): ------전체 데이터셋의 크기(size)를 반환합니다.
    return len (self.label)
  def __ geti tem __ (self, idx): ------ 전체 x와 y 데이터 중에 해당 idx번째의 데이터를 가져옵니다.
    sample = torch.tensor(self.label.iloc[idx,0:3]).int()
    label = torch.tensor(self.label.iloc[idx,3]).int()
    return sample, label
tensor_dataset = CustomDataset( ' .. /covtype.csv' ) ------ 데이터셋으로 covtype.csv를 사용합니다.
dataset = DataLoader(tensor_dataset, batch_size=4, shuffle=True )
```
* 파이토치에서 제공하는 데이터 셋 사용: MNIST, ImageNet 데이터셋 제공
```
pip install requests

import torchvision.transforms as transforms

mnist_transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5, ), (1.0, ))]) # 평균이 0.5, 표준편차가 1.0이 되도록 데이터의 분포(normalize)를 조정

from torchvision.datasets import MNIST
import requests
download_root = '내려받을 경로 지정'

train_dataset = MNIST(download_root, transform=mnist_transform, train=True, download=True)
valid_dataset = MNIST(download_root,transform=mnist_transform, train=False, download=True)
test_dataset = MNIST(download_root, transform=mnist_transform, train=False, download=True)
```

> **모델 정의**

* 모듈: 한 개 이상의 계층이 모여서 구성된 것, 모듈-모듈 결합 가능
* 모델: 최종적으로 원하는 네트워크

✅ 단순 신경망 정의 - nn.Module을 상속받지 않는 매우 단순한 모델을 만들 때 사용, 구현 쉽고 단순
```
model = nn.Linear(in_features=1, out_features=1, bias=True)
```

✅ nn.Module()을 상속하여 정의 - __init__() (모델에 사용될 모듈, 활성화 함수 등 정의) & forward() (모델에서 실행되어야 하는 연산 정의)
```
class MLP(Module):
def __init__ (self, inputs):
super(MLP, self). __init__ ()
self.layer = Linear(inputs , 1) #계층 정
self. activation = Sigmoid() #활성화 함수 정의
def forward (self, X):
X = self.layer(X)
X = self.activation(X)
return X
```


✅ Sequential 신경망 정의 - nn.Sequentail 사용시 __ init __()의 모델을 정의해주고 forward()의 계산을 더 가독성 있는 코드로 작성 / 각 모듈을 순차적 실행 / 모델의 계층이 복잡할수록 효과가 뛰어남

✅ 함수로 신경망 정의 - Sequential과 동일, 변수에 저장해둔 계층 재사용 가능 / 모델 복잡해짐 (이 경우 nn.Model 상속이 편리)

> **모델 파라미터 정의**

✅ 모델 학습 전, 정의할 파라미터

* 손실 함수: 학습하는 동안 출력과 실제값 사이의 오차 측정 / BCELoss(이진 분류), CrossEntropyLoss(다중 클래스 분류), MSELoss(회귀 모델)

* 옵티 마이저: 데이터와 손실 함수를 바탕으로 모델의 업데이트 방법 결정

  -- step() - 전달받은 파라미터 업데이트

  -- 모델 파라미터별 다른 기준 적용 가능

  -- 기본 클래스 - torch.optim.Optimizer

  -- zero_grad() - 옵티마이저에 사용된 파라미터들의 기울기를 0으로

  -- torch.optim.lr_scheduler - 에포크에 따라 학습률 조절


* 학습률 스케줄러: 미리 지정한 횟수의 에포크를 지날 때마다 학습률을 감소시켜줌. 전역 최소점 근처에서 학습률 감소

   -- optim.lr_scheduler.LambdaLR: 람다함수 이용

   -- optim.lr_scheduler.StepLR: 특정 step마다 학습률을 감마(gamma) 비율만큼 감소

   -- optim.lr_scheduler.MultiStepLR: 특정 단계가 아닌 지정된 에포크에만 감마 비율 감소

   -- optim.lr_scheduler.ExponentialLR: 에포크마다 이전 학습률에 감마만큼 곱함

   -- optim.lr_scheduler.CosineAnnealingLR: 학습률을 코사인함수의 형태처럼 변화. 학습률이 커지기도 작아지기도 함

   -- optim.lr_scheduler.ReduceLROnPlateau: 학습이 잘되고 있는지 아닌지에 따라 동적으로 학습률을 변화

* 지표: 훈련과 테스트 단계 모니터링

> **모델 훈련**

* 전역 최소점에 이를 때까지 파라미터 수정


✅ 훈련 절차





기울기 초기화 (opmizer.zero_grad()) : 기울기 누적계산(loss.backward())이 필요하지 않을 때 사용. ▶ 출력 계산 ▶ 오차 계산 ▶ 역전파 학습 ▶ 기울기 업데이트

* loss.backward() : 배치가 반복될 때마다 오차가 중첩적으로 쌓임.
```
for epoch in range(100):
  yhat = mode1(x_train)
  loss = criterion(yhat, y_train)
  optimizer. zero_grad () ------ 오차가 중첩적으로 쌓이지 않도록 초기화
  loss.backward()
  optimizer.step()
```

> **모델 평가**

(1) 함수 이용 평가

(2) 모듈 이용 평가
```
import torch
import torchmetrics
metric = torchmetrics.Accuracy() # 모델 평가(정확도) 초기화

n_batches = 10
for i in range(n_batches) :
preds = torch.randn(10,5).softmax(dim=-1)
target = torch.randint(5, (10,))

acc = metric(preds, target)
print(f'Accuracy on batch {i} : {acc}') # 현재 배치에서 모델 평가(정확도)

acc = metric.compute()
print(f'Accuracy on all data : {acc} ') # 모든 배치에서 모델 평가(정확도)
```

(3) 사이킷련 혼동 행렬 이용


> **훈련 과정 모니터링**

* 텐서보드 이용: 학습 중 파라미터 값이 어떻게 변화하는지 손쉽게 시각화 가능 / 성능 추적, 평가

* 텐서보드 설정 ▶ 텐서보드 기록 ▶ 모델 구조 파악













# [코드 필사]

In [1]:
import torch
print(torch.tensor([[1,2],[3,4]])) # 2차원 형태의 텐서 생성
print(torch.tensor([[1,2],[3,4]], device='cuda:0')) # GPU에 텐서 생성
print(torch.tensor([[1,2],[3,4]], dtype=torch.float64))  # dtpye이용해 텐서 생성

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], device='cuda:0')
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [2]:
# 텐서 > ndarray 변환
temp = torch.tensor([[1,2],[3,4]])
print(temp.numpy())

[[1 2]
 [3 4]]


In [4]:
temp = torch.tensor([[1,2],[3,4]], device="cuda:0")
print(temp.to("cpu").numpy()) # gpu상의 텐서를 cpu 텐서로 변환 후, ndarray 변환

[[1 2]
 [3 4]]


In [5]:
temp = torch.FloatTensor([1, 2, 3, 4, 5, 6, 7]) # 1차원 벡터 생성
print(temp[0], temp[1], temp[-1]) # 인덱스로 접근
print('-------------------------')
print(temp[2:5], temp[4:-1]) # 슬라이스로 접근

tensor(1.) tensor(2.) tensor(7.)
-------------------------
tensor([3., 4., 5.]) tensor([5., 6.])


In [6]:
v = torch.tensor([1, 2, 3])
w = torch.tensor([3, 4, 6])
print(w-v)

tensor([2, 2, 3])


In [8]:
temp = torch.tensor([ [1, 2], [3, 4] ])  # 2x2

print(temp.shape)
print('-----------------------')
print(temp.view(4, 1)) # 2x2 -> 4x1
print('-----------------------')
print(temp.view(-1))   # 2x2 -> 1차원
print('-----------------------')
print(temp.view(1, -1))  # 2x2 -> 1x4 # -1은 (1,?) 와 같은 의미
print('-----------------------')
print(temp.view(-1, 1))  # 2x2 -> 4X1

torch.Size([2, 2])
-----------------------
tensor([[1],
        [2],
        [3],
        [4]])
-----------------------
tensor([1, 2, 3, 4])
-----------------------
tensor([[1, 2, 3, 4]])
-----------------------
tensor([[1],
        [2],
        [3],
        [4]])


In [1]:
import torch.nn as nn
class MLP(nn.Module):
  def __init__(self):
      super(MLP, self).__init__()
      self.layer1 = nn.Sequential(
          nn.Conv2d(in_channels=3, out_channels=64, kernel_size=5),
          nn.ReLU(),
          nn.MaxPool2d(2))

      self.layer2 = nn.Sequential(
          nn.Conv2d(in_channels=64, out_channels=30, kernel_size=5),
          nn.ReLU(),
          nn.MaxPool2d(2))

      self.layer3 = nn.Sequential(
          nn.Linear(in_features=30*5*5, out_features=10, bias=True),
          nn.ReLU(inplace=True))

      def forward(self, x):
          x = self.layer1(x)
          x = self.layer2(x)
          x = x.view(x.size(0), -1)
          x = self.layer3(x)
          return x
model = MLP() # 모델에 대한 객체 생성

print("Printing children \n------------------------------")
print(list(model.children()))
print('\n\nPrinting Modules\n-------------------------------')
print(list(model.modules()))

Printing children 
------------------------------
[Sequential(
  (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU()
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
), Sequential(
  (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU()
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
), Sequential(
  (0): Linear(in_features=750, out_features=10, bias=True)
  (1): ReLU(inplace=True)
)]


Printing Modules
-------------------------------
[MLP(
  (layer1): Sequential(
    (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU()
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU()
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer3): Sequential(
    (0): Linear(in_features=750, out_features=10, bias=True)

In [2]:
def MLP(in_features=1, hidden_features=20, out_features=1):
    hidden = nn.Linear(in_features=in_features, out_features=hidden_features,
                       bias=True)
    activation = nn.ReLU()
    output = nn.Linear(in_features=hidden_features, out_features=out_features,
                       bias=True)
    net = nn.Sequential( hidden , activation , output)
    return net

In [5]:
!pip install torchmetrics

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.2/983.2 kB 60.7 MB/s eta 0:00:00


In [6]:
import torch
import torchmetrics

preds = torch.randn(10, 5).softmax(dim=-1)
target = torch.randint(5, (10, ))

acc = torchmetrics.functional.accuracy(preds, target, task="multiclass", num_classes=5)

In [7]:
!pip install tensorboard

In [ ]:
# import torch
# from torch.utils.tensorboard import SummaryWriter
# writer = SummaryWriter("/content/tensorboard") -- 모니터링에 필요한 값들이 저장될 위치

# for epoch in range(num_epochs):
#     model.train() #학습 모드로 전환
#     batch_loss = 0.0

#     for i, (x, y) in enumerate(dataloader):
#         x, y = x.to(device).float(), y.to(device).float()
#         outputs = model(x)
#         loss = criterion(outputs, y)
#         writer.add_scalar("Loss", loss, epoch) - 오차 기록
#         optimizer.zero.grad()
#         loss.backward()
#         optizer.step()

# writer.close()

In [ ]:
# 텐서보드 실행 명령
# tensorboard --logdir= .. /content/tensorboard --port=6006

 웹브라우저에 http://localhost:6006 입력